-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID,	REST_NAME,	FAVORITES
FROM (
        SELECT FOOD_TYPE, REST_ID,	REST_NAME,	FAVORITES, RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS FAVORITES_RANK
    FROM REST_INFO
    ORDER BY FAVORITES_RANK
) A
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC
